---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Heading
- type: document
  path: contents/posts
  label: Posts
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:, :year:, :month:, :day:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm install forestry:preview
